# Generated by Django 4.2.5 on 2023-09-11 04:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banners_image', models.ImageField(upload_to='banner_image')),
                ('principal_name', models.CharField(max_length=200)),
                ('vice_principal_name', models.CharField(max_length=200)),
                ('principal_image', models.ImageField(upload_to='principal_image')),
                ('vice_principal_image', models.ImageField(upload_to='vice_principal_image')),
                ('institution_image', models.ImageField(upload_to='institution_image')),
                ('news', ckeditor_uploader.fields.RichTextUploadingField()),
                ('principal_message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('vice_principal_message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('institution_history', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Institution_info',
                'verbose_name_plural': 'Institution_infos',
            },
        ),
    ]
