# Generated by Django 4.2.5 on 2023-09-11 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice_file', models.FileField(upload_to='notices/')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notice',
            },
        ),
    ]
