# Generated by Django 4.2.5 on 2023-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managing_committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='managing_committee_image')),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Managing_committee',
                'verbose_name_plural': 'Managing_committees',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Teacher_image')),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
            },
        ),
    ]
