# Generated by Django 4.2.5 on 2023-09-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_managing_committee_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='p_image')),
            ],
            options={
                'verbose_name': 'Photo gallery',
                'verbose_name_plural': 'Photo gallery',
            },
        ),
        migrations.CreateModel(
            name='Video_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('youtube_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Video gallery',
                'verbose_name_plural': 'Video gallery',
            },
        ),
        migrations.AlterModelOptions(
            name='institution_info',
            options={'verbose_name': 'Institution info', 'verbose_name_plural': 'Institution info'},
        ),
        migrations.AlterModelOptions(
            name='managing_committee',
            options={'verbose_name': 'Managing committee', 'verbose_name_plural': 'Managing committees'},
        ),
    ]
