# Generated by Django 4.2.5 on 2023-09-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_classroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_class', models.CharField(choices=[('class_1', 'class_1'), ('class_2', 'class_2'), ('class_3', 'class_3'), ('class_4', 'class_4'), ('class_5', 'class_5'), ('class_6', 'class_6'), ('class_7', 'class_7'), ('class_8', 'class_8'), ('class_9', 'class_9'), ('class_10', 'class_10'), ('inter_first_year', 'inter_first_year'), ('inter_second_year', 'inter_second_year')], max_length=200)),
                ('student_class_roll', models.IntegerField()),
                ('student_name', models.CharField(max_length=200)),
                ('student_image', models.ImageField(upload_to='student_image')),
                ('guardian_number_1', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('select_sections', models.CharField(choices=[('ক', 'ক'), ('খ', 'খ'), ('গ', 'গ'), ('ঘ', 'ঘ'), ('ঙ', 'ঙ'), ('চ', 'চ'), ('ছ', 'ছ')], max_length=5)),
            ],
            options={
                'verbose_name': 'Add Student Info',
                'verbose_name_plural': 'Add Student info',
            },
        ),
    ]
