# Generated by Django 4.2.5 on 2023-09-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_add_student_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_student_info',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
