# Generated by Django 4.2.5 on 2023-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_add_student_info_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo_gallery',
            options={'verbose_name_plural': 'Photo gallery'},
        ),
        migrations.AlterModelOptions(
            name='video_gallery',
            options={'verbose_name_plural': 'Video gallery'},
        ),
        migrations.AlterField(
            model_name='add_student_info',
            name='select_class',
            field=models.CharField(choices=[('class_1', 'প্রথম শ্রেণী'), ('class_2', 'দ্বিতীয় শ্রেণী'), ('class_3', 'class_3'), ('class_4', 'class_4'), ('class_5', 'class_5'), ('class_6', 'class_6'), ('class_7', 'class_7'), ('class_8', 'class_8'), ('class_9', 'class_9'), ('class_10', 'class_10'), ('inter_first_year', 'inter_first_year'), ('inter_second_year', 'inter_second_year')], max_length=200),
        ),
    ]
