# Generated by Django 4.2.5 on 2023-09-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_add_student_info_select_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_student_info',
            options={'ordering': ['student_class_roll'], 'verbose_name_plural': 'Add Student info'},
        ),
        migrations.AddField(
            model_name='result',
            name='board_result_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
