# Generated by Django 4.2.5 on 2023-09-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_result_result_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('massage', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contact Form',
            },
        ),
        migrations.CreateModel(
            name='contatc_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('number1', models.CharField(max_length=15)),
                ('number2', models.CharField(blank=True, max_length=15, null=True)),
                ('email1', models.CharField(max_length=50)),
                ('email2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contatc Addresss',
            },
        ),
    ]
